import pygame as pg

#Constants

#GAME SETUP SETTINGS
GAME_NAME = 'WE-SWITCH 2D'
SCREEN_WIDTH, SCREEN_HEIGHT = 1600,900
FPS = 60

#PATHS
IMAGE_PATH = 'Assets/images/'
SPRITE_PATH = 'Assets/sprites/'
SOUND_PATH = 'Assets/sounds/'

#PLAYER CONFIG
PLAYER_SIZE = 800
PLAYER_PIXEL_SIZE = 100
PLAYER_IDLE_SPEED = 0.12
GRAVITY = 5

#Global Variables

#GAME SETUP SETTINGS  
gAME_STATE = True
iS_FULLSCREEN = False
sCENE = 'MAIN_GAME'

#PLAYER CONTROLS
PLAYER1_KEY = pg.K_f
PLAYER2_KEY = pg.K_j
FULLSCREEN_KEY = pg.K_BACKSPACE
QUIT_KEY = pg.K_ESCAPE