import pygame as pg

#GAME SETUP SETTINGS
GAME_NAME = 'WE-SWITCH 2D'
SCREEN_WIDTH, SCREEN_HEIGHT = 1600,900
GAME_STATE = True
SCENE = 'MAIN_GAME'
FPS = 60

#PATHS
IMAGE_PATH = 'Assets/images/'
SPRITE_PATH = 'Assets/sprites/'
SOUND_PATH = 'Assets/sounds/'

#PLAYER CONFIG
PLAYER_SIZE = 600
PLAYER_PIXEL_SIZE = 100
PLAYER_IDLE_SPEED = 0.12
PLAYER1_KEY = pg.K_f
PLAYER2_KEY = pg.K_j
GRAVITY = 5