#GAME SETUP SETTINGS
GAME_NAME = 'WE-SWITCH 2D'
SCREEN_WIDTH, SCREEN_HEIGHT = 1200,675
GAME_STATE = True
SCENE = 'MAIN_GAME'
FPS = 60

#PATHS
ASSETS_PATH = 'Assets/'

#PLAYER CONFIG
PLAYER_SIZE = 600
PLAYER_PIXEL_SIZE = 100
PLAYER_IDLE_SPEED = 0.12